### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by conspacer** [thomascube/roundcube-plugin-kolab-2fa#1]
I performed the install as directed (git clone, composer install for dependencies and enabling in RC config file), but nothing has shown in the RC settings panel so far.

**Questions:**

1.   Do I need a backend for simple TOTP 2FA (we are using mysql for RC)
2.   Do I need to enable or do anything else to get this going?
3.   Where are the log files kept for errors and troubleshooting? (I checked RC logs, nothing shows re. this plugin)

**Comment by jjellinek** [comment]
I'm also having trouble installing this. roundcube logs to syslog by default, but you can change that in the config to file and it goes into the logs directory. That helps a bit.

I don't believe a back end is needed, it is provided by the otphp library (one of the dependencies) but it's here that I am falling down.

In your case, did you add kolab-2fa to the plugin array in the main roundcube config file?

My error log says:-

PHP Fatal error:  Class 'OTPHP\TOTP' not found in /home/hastymail/public_html/latest/plugins/kolab_2fa/lib/Kolab2FA/Driver/TOTP.php on line 55

which implies that the library isn't being found/loaded but I have no idea how to fix that.

As far as I can see the library is in the correct location:-

~/public_html/latest/plugins/kolab_2fa/vendor/spomky-labs/otphp/lib$ ls -al
total 40
drwxr-xr-x 2 hastymail hastymail 4096 Nov 15  2015 .
drwxr-xr-x 3 hastymail hastymail 4096 Feb 23 02:17 ..
-rw-r--r-- 1 hastymail hastymail 2960 Nov 15  2015 Factory.php
-rw-r--r-- 1 hastymail hastymail  547 Nov 15  2015 HOTPInterface.php
-rw-r--r-- 1 hastymail hastymail 1758 Nov 15  2015 HOTP.php
-rw-r--r-- 1 hastymail hastymail 3207 Nov 15  2015 OTPInterface.php
-rw-r--r-- 1 hastymail hastymail 7710 Nov 15  2015 OTP.php
-rw-r--r-- 1 hastymail hastymail  697 Nov 15  2015 TOTPInterface.php
-rw-r--r-- 1 hastymail hastymail 2208 Nov 15  2015 TOTP.php

**Comment by thomascube** [comment]
The 3rd party libs need to be installed via Composer from the root directory of your Roundcube installations. Thus they're supposed to live in ~/public_html/latest/vendor/

This should all be done right when you install the plugin via composer from the [Roundcube plugin repository](https://plugins.roundcube.net/packages/kolab/kolab_2fa).

**Comment by jjellinek** [comment]
Ah, I don't know why I didn't try that! I was using composer commands from within the plugin directory. Perhaps the readme could clarify for those like me that don't deal with rc plugins regularly that these commands should be run from the roundcube root? I'll give this a go soon. Meanwhile I got TOTP working with a different plugin.

**Comment by conspacer** [comment]
@thomascube I am doing a fresh RC install in a few days, Ill do a strict composer install as you directed and update with feedback.

**Comment by thomascube** [comment]
No feedback
