### ISSUE TITLE
How to enable?

### ISSUE THREAD

**Issue by lbdroid** [thomascube/roundcube-plugin-kolab-2fa#12]
Roundcubemail v1.5.2 on Rocky Linux 8

I have the plugin installed at plugins/kolab_2fa,
I copied config.inc.php.dist to config.inc.php (left as default with driver as totp and storage as roundcube),
I installed the required plugins per the README (composer install ....),
I have the plugin added at config/config.inc.php in $config['plugins'] array,
I can add 2nd factor at Settings --> Multi-Factor Auth,
But upon attempt to log in, it does NOT query for the second factor.

What am I missing?

**Comment by lbdroid** [comment]
Ah, this looks like it may be a BUG.

When I use a FULL username as "user@host.tld", it prompts for the second factor. If I try to log in with just "user", it skips it.
So probably connected with the use of $rcmail_config['username_domain'].

**Comment by thomascube** [comment]
Please see the note in our README: "For bug reports and pull requests, please go to https://kolab.org/"
