### ISSUE TITLE
Disable authentication methods for a user or reset user preferences

### ISSUE THREAD

**Issue by leonardomarino** [thomascube/roundcube-plugin-kolab-2fa#2]
I have installed the plugin and it is working fine. However, I need to reset the user preferences to disable the current authentication method. How do I do that?

**Comment by leonardomarino** [comment]
One more thing the storage backend is in Roundcube. It is not clear to me how can I remove the configuration from the database. I have tried disabling the supported method in $config['kolab_2fa_drivers'], in my case is 'yubikey' without any luck.

**Comment by thomascube** [comment]
You can disable a user's 2nd factor authentication by removing the according properties from the user prefs. There's a shell script for this in Roundcube:
```
bin/moduserprefs.sh --user=<user-id-from-db> --delete kolab_2fa_blob
```

This should "solve" the reported issue for you.

> @thomascube Would it be possible to add support for duosecurity/duo_php

Please request this feature at the [Kolab community](https://kolab.org). Remember this is only a mirror repository and development happens at Kolab.
