### ISSUE TITLE
Settings view error on RoundCube 1.4.7

### ISSUE THREAD

**Issue by shappyking** [thomascube/roundcube-plugin-kolab-2fa#5]
I was able to successfully install the plugin using composer but when i go to the setting page and click on Multi-Factor Auth i get an error that i listed below.

FILE NOT FOUND
The requested resource was not found!
Please contact your server-administrator.
Failed request: /cpsess5784839230/3rdparty/roundcube/index.php?_task=settings&_action=plugin.kolab-2fa

**Comment by jedvod** [comment]
I'm also experiencing this issue

**Comment by thomascube** [comment]
Please see the note in the readme file:
> This is a clone from https://git.kolab.org/diffusion/RPK/
> For bug reports and pull requests, please go to https://kolab.org/
