### ISSUE TITLE
3.5.5 Code verification for Mobile App (TOTP) failed

### ISSUE THREAD

**Issue by RvdHout** [thomascube/roundcube-plugin-kolab-2fa#7]
I would like to enable TOTP for use with Microsoft/Google Authenticator mobile app, using Roundcube 1.4.11 (PHP 7.4, IIS, MS Server 2019) 

I installed the plugin, enabled composer and ran composer.phar to install all required 3rd party libraries... everything seems to have worked, no errors returned by composer.phar or in general roundcube error.log

Plugin loads fine in roundcube, but i am unable to verify my 6 char TOTP code, it always returns:

> Code verification for Mobile App (TOTP) failed

I tried both Google Authenticator mobile app and Microsoft Authenticator mobile app, both fail with TOTP
console.log doesn't display any error(s)

FYI, HOTP driver works for Google Authenticator mobile app, but not for Microsoft Authenticator mobile app

**Comment by RvdHout** [comment]
No one?

If it fails for some reason you would expect the error is logged somewhere....
Or maybe i configured it wrong?  I am not using LDAP or something, eg: $config['kolab_2fa_storage'] = 'roundcube';

The rest of the setting besides $config['kolab_2fa_drivers'] = array('totp', 'hotp'); i kept at their defaults

**Comment by RvdHout** [comment]
I think i might have found something that may be causing this (i do not know if it is only Windows/IIS related or a issue on itself)

>         // PHP gets a string, but we're comparing integers.
>         $code = (int)$code;

If i comment out line 81, TOTP seems to generate valid QR codes for TOTP 
https://github.com/thomascube/roundcube-plugin-kolab-2fa/blob/master/lib/Kolab2FA/Driver/TOTP.php#L80-L81

**Comment by thomascube** [comment]
Please see the note in the readme file:

> This is a clone from https://git.kolab.org/diffusion/RPK/
> For bug reports and pull requests, please go to https://kolab.org/

**Comment by thomascube** [comment]
I failed to forward the issue to the git.kolab.org bug tracker due to a system error on their side so here's a fix in this mirrored repository.

**Comment by thomascube** [comment]
Fixed in version/tag 3.5.5.2
